version: "3.7"
services:
  ms-configserver:
    image: pedrodiaz/ms-configserver:v1
    container_name: ms-configserver
    ports:
      - "8888:8888"
  ms-discovery:
    image: pedrodiaz/ms-discovery:v1
    container_name: ms-discovery
    ports:
      - "8889:8889"
    depends_on:
      - ms-configserver
  ms-api-gateway:
    image: pedrodiaz/ms-api-gateway:v1
    container_name: ms-api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - ms-configserver
      - ms-discovery
  ms-customer:
    image: pedrodiaz/ms-customer:v1
    container_name: ms-customer
    ports:
      - "8080:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
  ms-product:
    image: pedrodiaz/ms-product:v1
    container_name: ms-product
    ports:
      - "8081:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
  ms-customerproduct:
    image: pedrodiaz/ms-customerproduct:v1
    container_name: ms-customerproduct
    ports:
      - "8082:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
      - ms-customer
      - ms-product
  ms-operation:
    image: pedrodiaz/ms-operation:v1
    container_name: ms-operation
    ports:
      - "8083:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
      - ms-customer
      - ms-product
      - ms-customerproduct
  ms-shopping:
    image: pedrodiaz/ms-shopping:v1
    container_name: ms-shopping
    ports:
      - "8084:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
      - ms-customer
      - ms-product
      - ms-customerproduct
  ms-payment:
    image: pedrodiaz/ms-payment:v1
    container_name: ms-payment
    ports:
      - "8085:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
      - ms-customer
      - ms-product
      - ms-customerproduct
  ms-querybalance:
    image: pedrodiaz/ms-querybalance:v1
    container_name: ms-querybalance
    ports:
      - "8086:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
      - ms-customer
      - ms-product
      - ms-customerproduct
      - ms-operation
      - ms-shopping
      - ms-payment
  ms-wiretransfer:
    image: pedrodiaz/ms-wiretransfer:v1
    container_name: ms-wiretransfer
    ports:
      - "8087:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
      - ms-customer
      - ms-product
      - ms-customerproduct
      - ms-operation
      - ms-shopping
      - ms-payment
      - ms-querybalance