version: "3.7"
services:
  ms-configserver:
    image: ms-configserver
    container_name: ms-configserver
    ports:
      - "8888:8888"
  ms-discovery:
    image: ms-discovery
    container_name: ms-discovery
    ports:
      - "8889:8889"
  ms-api-gateway:
    image: ms-api-gateway
    container_name: ms-api-gateway
    ports:
      - "8000:8000"
  db_customer:
    image: mongo
    container_name: db_customer
    environment:
      - "MONGO_INITDB_DATABASE=db_customer"
    ports:
      - "27017:27017"
    volumes:
      - ~/Desktop/Bootcamp/Mongodb/db_customer:/data/db
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
  ms-customer:
    image: ms-customer
    container_name: ms-customer
    ports:
      - "8080:8080"
    depends_on:
      - db_customer
  db_product:
    image: mongo
    container_name: db_product
    environment:
      - "MONGO_INITDB_DATABASE=db_product"
    ports:
      - "27018:27017"
    volumes:
      - ~/Desktop/Bootcamp/Mongodb/db_product:/data/db
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
  ms-product:
    image: ms-product
    container_name: ms-product
    ports:
      - "8081:8080"
    depends_on:
      - db_product
  db_customerProduct:
    image: mongo
    container_name: db_customerProduct
    environment:
      - "MONGO_INITDB_DATABASE=db_customerProduct"
    ports:
      - "27019:27017"
    volumes:
      - ~/Desktop/Bootcamp/Mongodb/db_customerProduct:/data/db
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
  ms-customerproduct:
    image: ms-customerproduct
    container_name: ms-customerproduct
    ports:
      - "8082:8080"
    depends_on:
      - db_customerProduct
      - ms-customer
      - db_product
  db_operation:
    image: mongo
    container_name: db_operation
    environment:
      - "MONGO_INITDB_DATABASE=db_operation"
    ports:
      - "27020:27017"
    volumes:
      - ~/Desktop/Bootcamp/Mongodb/db_operation:/data/db
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
  ms-operation:
    image: ms-operation
    container_name: ms-operation
    ports:
      - "8083:8080"
    depends_on:
      - db_operation
      - ms-customerproduct
  db_payment:
    image: mongo
    container_name: db_payment
    environment:
      - "MONGO_INITDB_DATABASE=db_payment"
    ports:
      - "27022:27017"
    volumes:
      - ~/Desktop/Bootcamp/Mongodb/db_payment:/data/db
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
  ms-payment:
    image: ms-payment
    container_name: ms-payment
    ports:
      - "8085:8080"
    depends_on:
      - db_payment
      - ms-customerproduct
  db_shopping:
    image: mongo
    container_name: db_shopping
    environment:
      - "MONGO_INITDB_DATABASE=db_shopping"
    ports:
      - "27021:27017"
    volumes:
      - ~/Desktop/Bootcamp/Mongodb/db_shopping:/data/db
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
  ms-shopping:
    image: ms-shopping
    container_name: ms-shopping
    ports:
      - "8084:8080"
    depends_on:
      - db_shopping
      - ms-customerproduct
  ms-querybalance:
    image: ms-querybalance
    container_name: ms-querybalance
    ports:
      - "8086:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
      - ms-operation
      - ms-payment
      - ms-shopping
  ms-wiretransfer:
    image: ms-wiretransfer
    container_name: ms-wiretransfer
    ports:
      - "8087:8080"
    depends_on:
      - ms-configserver
      - ms-discovery
      - ms-api-gateway
      - ms-operation
      - ms-payment
      - ms-shopping