version: "3"
services:
  sonarqube:
    image: sonarqube:8.9.7-community
    restart: always
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  init:
      image: bash
      privileged: true
      user: root
      volumes:
        - ./init.sh:/mnt/init.sh 
      command: ["sh", "-e", "/mnt/init.sh"]
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./postgresql/conf:/var/lib/postgresql
      - ./postgresql/data:/var/lib/postgresql/data