spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: customer-service
        uri: lb://CUSTOMER-SERVICE
        predicates[0]: Path=/api/v1/customers/**,/api/v1/customerType/**
      routes[1]:
        id: product-service
        uri: lb://PRODUCT-SERVICE
        predicates[0]: Path=/api/v1/products/**,/api/v1/productType/**
      routes[2]:
        id: customerproduct-service
        uri: lb://CUSTOMERPRODUCT-SERVICE
        predicates[0]: Path=/api/v1/customerActivesProducts/**,/api/v1/customerPassivesProducts/**
      routes[3]:
        id: operation-service
        uri: lb://OPERATION-SERVICE
        predicates[0]: Path=/api/v1/operations/**,/api/v1/operationTypes/**
      routes[4]:
          id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates[0]: Path=/api/v1/payments/**
      routes[5]:
        id: shopping-service
        uri: lb://SHOPPING-SERVICE
        predicates[0]: Path=/api/v1/shoppings/**
      routes[6]:
        id: querybalance-service
        uri: lb://QUERY-BALANCE-SERVICE
        predicates[0]: Path=/api/v1/balance/**
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8889/eureka/